#!/bin/bash -x
# ubuntu 16.04 LTS packages installation

#https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt
#sudo dpkg --force-all -i *
#sudo apt-get install -f	
#above two command will install offline downloaded packages ,
#  downloaded packages are on Delta server , pathj is  `userBackupDrive/Admin-Data/ubuntuPackageInstallation`
# if need to install from internet use below script functions
#
## -f, --fix-broken
## Fix; attempt to correct a system with broken dependencies in place.
#When dpkg installs a package and a package dependency is not satisfied, it leaves the package in an "unconfigured" state and that package is considered broken.
#The sudo apt-get install -f command tries to fix this broken package by installing the missing dependency.		
	

	docker () {

sudo apt-get update
sudo apt-get install apt-transport-https  ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository  "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs)  stable"

		sudo apt-get update
		sudo apt-get install docker-ce docker-ce-cli containerd.io -y

	echo "Verify that Docker Engine is installed correctly by running the hello-world image"
		sudo docker run hello-world
		sudo docker images

## with user root
sudo mkdir /home/docker-data
vim /etc/docker/daemon.json
	{
    "data-root": "/home/docker-data",
    "storage-driver": "overlay2",
    "registry-mirrors": ["http://192.168.5.13:5000"],
    "insecure-registries" : ["192.168.5.13:5000"]
	}

	systemctl stop docker
	systemctl start docker

	echo "Check if the new config has taken effect - docker images should now return nothing as it is looking"
		docker images
		docker run hello-world
}

	wine () {
sudo dpkg --add-architecture i386
wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo apt-key add winehq.key
sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
sudo apt update
sleep 2
sudo apt install --install-recommends winehq-stable -y

}


	JAVA(){
sudo mkdir /usr/lib/jvm/ -p
cd  /usr/lib/jvm/
wget http://192.168.5.140/download/jdk-8u241-linux-x64.tar.gz    ## or download from `userBackupDrive/Admin-Data/ubuntuPackageInstallation`
sudo tar -xf jdk-8u241-linux-x64.tar.gz

echo "export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_241"  >> ~/.bashrc 
source ~/.bashrc
echo "export PATH=$PATH:$HOME/bin:$JAVA_HOME/bin" >> ~/.bashrc
source ~/.bashrc

sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.8.0_241/bin/java 1             
sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk1.8.0_241/bin/javac 1       
sudo update-alternatives --config java						  ##  to change java version
sudo update-alternatives --config javac						# to change javac version

}

	netbeans () {
# run the  netbeans8.2.sh manually and install it with GUI
}

	APACHE() {
sudo apt-get install apache2 -y
sudo systemctl enable apache2		
sudo systemctl start apache2

}


	MYSQL() {
sudo apt-get install mysql-server -y
s
}

	ELASTICSEARCH() {
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo apt-get install apt-transport-https -y
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
sudo apt-get update 
sudo apt-get install elasticsearch -y

}

	sugarcrm () {
## for sugarcrm , java, elasticsearch, apache, mysql, php required
#java -v
#elasticsearch 5.x - 6.x
#apache
#mysql
#php
sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install -y libapache2-mod-php7.3 php-common php7.3 php7.3-bcmath php7.3-cli php7.3-common php7.3-curl php7.3-gd php7.3-imap php7.3-json php7.3-mbstring php7.3-mysql php7.3-opcache php7.3-pgsql php7.3-readline php7.3-xml php7.3-zip
#php 7.1 ##sudo apt install -y libapache2-mod-php7.1 php-common php7.1 php7.1-bcmath php7.1-cli php7.1-common php7.1-curl php7.1-gd php7.1-imap php7.1-json php7.1-mbstring php7.1-mysql php7.1-opcache php7.1-pgsql php7.1-readline php7.1-xml php7.1-zip

echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php         ## to te4st php version and php page  working or not
## test http://localhost/phpinfo.php

cd /var/www/html/
tar -xf sugar.tar.gz

mv sugar-9xxx sugarcrm
chmod 777 sugarcrm

#https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-ubuntu-16-04
sudo a2enmod rewrite
sudo systemctl restart apache2

## steps for .htaccess in ubuntu
step1
vim /etc/apache2/sites-available/000-default.conf

<VirtualHost *:80>
## add below line of Directory  between virtualhost 
    <Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>
## till here 
    . . .
</VirtualHost>

step2
echo "RewriteEngine on" >> /var/www/html/.htaccess

step3
sudo systemctl restart apache

}


	MELD() {
sudo apt install meld -y
}

	SUBLIME() {
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo apt install apt-transport-https -y
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text-stable.list
sudo apt-get update 
sudo apt install sublime-text -y

}

	GIT() {
sudo apt-get install git -y
sudo apt-get install git-flow -y

}

	NODE() {
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

node -v
npm -v
}

	VISUALSTUDIO() {
wget http://192.168.5.140/code_1.45.1-1589445302_amd64.deb
dpkg -i code_1.45.1-1589445302_amd64.deb

}

	NOTEPADPLUS() {
sudo apt-get install snapd snapd-xdg-open
sudo snap install notepad-plus-plus -y

}

	COMPOSER() {
sudo apt install composer -y

}

WORKBENCH(){
sudo apt install mysql-workbench 

}

##--------script start here--------
wine

java
apache
mysql
elasticsearch
meld
sublime
git
node
visualstudio
notepadplus
composer
WORKBENCH
